In [ ]:
import numpy as np
np.__version__

'2.0.2'

1)Створити матрицю 3*3, заповнити її цілими випадковими числами від 1 до 5

In [ ]:
matrix = np.random.randint(1,6, size=(3,3))

matrix

array([[5, 3, 3],
       [3, 1, 1],
       [3, 4, 2]])

2)Обчислити визначник матриці

In [ ]:
det = np.linalg.det(matrix)

det

np.float64(8.000000000000002)

3)Знайти добуток усіх елементів матриці

In [ ]:
product = np.prod(matrix)

product

np.int64(3240)

In [ ]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1 * prod_2 * prod_3

np.int64(3240)

4)Знайти суму всіх елементів

In [ ]:
sum = np.sum(matrix)

sum

np.int64(25)

5)Обчислити найбільший, найменший елементи

In [ ]:
max_element = np.max(matrix)
print("Найбільший елемент матриці", max_element)

min_element = np.min(matrix)
print("Найменший елемент матриці", min_element)

Найбільший елемент матриці 5
Найменший елемент матриці 1


6)Знайти середнє значення елементів матриці

In [ ]:
mean = np.mean(matrix)
print("Середнє значення елемента матриці", mean)

Середнє значення елемента матриці 2.7777777777777777


7)Знайти матрицю, що складається з квадратних коренів

In [ ]:
sqrt_matrix = np.sqrt(matrix)

print("Матриця квадратних коренів:")
print(sqrt_matrix)

Матриця квадратних коренів:
[[2.23606798 1.73205081 1.73205081]
 [1.73205081 1.         1.        ]
 [1.73205081 2.         1.41421356]]


8)Обчислити суму елементів кожного рядка. Відповідь записати як веткор-стовпчик

In [ ]:
row_sums = np.sum(matrix, axis = 1).reshape(-1, 1)

print("Сума елементів кожного рядка:")
print(row_sums)
#В результаті отримали вектор-стовпчик

Сума елементів кожного рядка:
[[11]
 [ 5]
 [ 9]]


9)Створити вектор, що містить 25 елементів. Заповнити числами від 0 до 9. Відсортувати числа за спаданням.

In [ ]:
vector = np.random.randint(0, 10, size = 25)

print("Початковий вектор:")
print(vector)

#Сортуємо числа за спаданням
sorted_vector = np.sort(vector)[::-1]

print("Вектор після сортування за спаданням:")
print(sorted_vector)

Початковий вектор:
[4 5 3 3 6 7 9 8 3 0 6 8 6 2 9 2 4 6 3 7 5 1 5 6 5]
Вектор після сортування за спаданням:
[9 9 8 8 7 7 6 6 6 6 6 5 5 5 5 4 4 3 3 3 3 2 2 1 0]


10)Знайти моду, медіану, середнє, максимальне, мінімальне значення

In [ ]:
from scipy import stats
#Знаходимо моду
mode = stats.mode(vector)

#Знаходимо медіану
median = np.median(vector)

#Знаходимо середнє
mean = np.mean(vector)

#Знаходимо максимавлььне значення
max_value = np.max(vector)

#Знаходимо мінімальне значення
min_value = np.min(vector)

print("Мода:", mode)
print("Медіана:", median)
print("Середнє:", mean)
print("Максимальне значення:", max_value)
print("Мінімальне значення:", min_value)

Мода: ModeResult(mode=np.int64(6), count=np.int64(5))
Медіана: 5.0
Середнє: 4.92
Максимальне значення: 9
Мінімальне значення: 0


11)Створити два матриці 4*4, заповнені числами віл 1 до 10. Обчислити суму, різницю, поелементний добуток, частку.

In [ ]:
matrix1 = np.random.randint(1, 11, size=(4,4))
matrix2 = np.random.randint(1, 11, size=(4,4))

print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

Матриця 1:
[[ 1  6  3  3]
 [ 4  9  5  5]
 [ 2  7  7  6]
 [ 6  6  3 10]]

Матриця 2:
[[ 8  6  4  5]
 [ 3  3  6  4]
 [ 8  1 10  7]
 [ 2  2  5  8]]


In [ ]:
#Обчислити суму матриць
matrix_sum = matrix1 + matrix2

#Обчислити різницю матриць
matrix_diff = matrix1 - matrix2

#Обчислюємо поелементрий добуток матриць
matrix_product = matrix1 - matrix2

#Обчислюємо поелементну частку матриць
#Для запобігання діленню а нуль, використовуємо np.divide з параметром where
matrix_division = np.divide(matrix1, matrix2, where=(matrix2!=0))

print("\nСума матриць:")
print(matrix_sum)

print("\nРізниця матриць:")
print(matrix_diff)

print("\nПоелементий добуток матриць:")
print(matrix_product)

print("\nПоелементна частка матриць:")
print(matrix_division)


Сума матриць:
[[ 9 12  7  8]
 [ 7 12 11  9]
 [10  8 17 13]
 [ 8  8  8 18]]

Різниця матриць:
[[-7  0 -1 -2]
 [ 1  6 -1  1]
 [-6  6 -3 -1]
 [ 4  4 -2  2]]

Поелементий добуток матриць:
[[-7  0 -1 -2]
 [ 1  6 -1  1]
 [-6  6 -3 -1]
 [ 4  4 -2  2]]

Поелементна частка матриць:
[[0.125      1.         0.75       0.6       ]
 [1.33333333 3.         0.83333333 1.25      ]
 [0.25       7.         0.7        0.85714286]
 [3.         3.         0.6        1.25      ]]
